---
version: '3'

services:
  bet-manager-api:
    image: bet-manager-api
    container_name: bet-manager-api
    build:
      context: .
      args:
        - phoenix_port=${PORT}
    links:
      - bet-manager-db
    depends_on:
      - bet-manager-db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/opt/app
    environment:
      MIX_ENV: "${MIX_ENV}"
      PORT: "${PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_DATABASE_TEST: "${DB_DATABASE_TEST}"
      DB_HOST: "${DB_HOST}"
      DB_POOL: "${DB_POOL}"
    networks:
      - bet-manager
  bet-manager-db:
    container_name: bet-manager-db
    image: postgres:12.1
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - bet-manager

networks:
  bet-manager:
    driver: bridge

volumes:
  db-data:
    driver: local
