---
name: Elixir CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: bitwalker/alpine-elixir-phoenix:latest
      env:
        MIX_ENV: test

    services:
      db:
        image: postgres:9.6
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          PGDATA: /var/lib/postgresql/data/pgdata

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies and Setup Database
      run: |
        mix deps.get
    - name: Run Tests
      run: |
        mix ecto.setup
        mix test
      env:
        MIX_ENV: test
        PORT: 4000
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_DATABASE: bet_manager_dev
        DB_DATABASE_TEST: bet_manager_test
        DB_HOST: db
        DB_POOL: 10
