---
name: Elixir CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    services:
      postgres:
        image: postgres:9.6
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          PGDATA: /var/lib/postgresql/data/pgdata
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y build-essential
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Setup Database and Run Tests
      run: |
        mix ecto.setup
        mix test
      env:
        MIX_ENV: test
        PORT: 4000
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_DATABASE: bet_manager_dev
        DB_DATABASE_TEST: bet_manager_test
        DB_HOST: postgres
        DB_POOL: 10
